### ISSUE TITLE
[FEATURE] Make "START" act as "A" button when -y is passed

### ISSUE THREAD

**Issue by shantigilbert** [lethal-guitar/TvTextViewer#18]
Many times people seem to press `START` to choose the `Yes` or `No` options, but it seems that if you press `START` it acts as if the `No` options  was chosen even if the `Yes` is highlighted. 

An alternative (and probably better way) would be to make `START` act as the `A` button so that the highlighted item is chosen, but I can't seem to fully understand how or where the `START` button is defined.

**Comment by lethal-guitar** [comment]
Makes sense! Start is handled here: https://github.com/lethal-guitar/TvTextViewer/blob/3e95de9170dd0cc6f7f3eb46935d911ff05e480c/main.cpp#L236

The easiest would probably be to change that code to return 21 instead of 0 in case the yes/no button mode is enabled.

To treat start as A in general, we could add another mapping here: https://github.com/lethal-guitar/TvTextViewer/blob/3e95de9170dd0cc6f7f3eb46935d911ff05e480c/imgui_impl_sdl.cpp#L342

We would still need to change the other code though, because the start button handling currently happens before ImGui sees the event. It would also mean that start would not quit anymore if the user has selected the text box instead of the buttons.

**Comment by shantigilbert** [comment]
> It would also mean that start would not quit anymore if the user has selected the text box instead of the buttons.

How about we use `Select` (or whatever the equivalent is) for Quit and `Start` to be handled as `A` ?
